name: Release Crate

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml

  release:
    name: Release
    environment: crates.io
    runs-on: ubuntu-latest
    needs: tests

    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      SCCACHE_GHA_ENABLED: true

    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - uses: mozilla-actions/sccache-action@v0.0.6

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PLZ_TOKEN }}

      - name: Release
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
