name: tests
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Rust Toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: Swatinem/rust-cache@v2

      - name: Configure sccache
        run: |
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV

      - uses: mozilla-actions/sccache-action@v0.0.3

      - name: Install Code Coverage Dependencies
        run: |
          cargo install grcov
          rustup component add llvm-tools-preview

      - name: Test w/Coverage
        if: always()
        run: make coverage

      - uses: codecov/codecov-action@v3
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/coverage/tests.lcov
          name: awsipranges-rust
