name: test
on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update

      - name: Test
        run: make test

      - name: Analyze Code Coverage
        run: make coverage

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/coverage/tests.lcov
          name: awsipranges-rust
