name: tests
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-14
          - macos-13

    name: tests-${{ matrix.os }}

    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      SCCACHE_GHA_ENABLED: true

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - uses: Swatinem/rust-cache@v2

      - uses: mozilla-actions/sccache-action@v0.0.3

      - name: Install Code Coverage Dependencies
        run: |
          cargo install grcov
          rustup component add llvm-tools-preview

      - name: Test w/Coverage
        run: make coverage

      - name: Upload Coverage Report
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/coverage/tests.lcov
          name: awsipranges-rust
