name: Tests
on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    env:
      RUST_BACKTRACE: full
      RUST_LOG: debug
      RUSTC_WRAPPER: sccache
      SCCACHE_GHA_ENABLED: true

    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - uses: mozilla-actions/sccache-action@v0.0.6

      - name: Install code coverage dependencies
        run: |
          cargo install grcov
          rustup component add llvm-tools-preview

      - name: Checkout
        uses: actions/checkout@v4

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Lint code
        run: cargo clippy

      - name: Test w/coverage
        run: make coverage

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        if: github.ref == 'refs/heads/main'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/coverage/tests.lcov
          name: awsipranges
